# Generated by Django 6.0.8 on 2026-09-19 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
