# Generated by Django 6.0.8 on 2026-09-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_address_options_alter_profile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="membership",
            field=models.CharField(
                choices=[("regular", "Zwykłe"), ("premium", "Premium")],
                default="regular",
                help_text="Poziom członkostwa — premium nadawane automatycznie po przekroczeniu progu i nigdy nie odbierane (ADR 0023)",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="membership_granted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data nadania premium; puste dla zwykłego członkostwa",
                null=True,
            ),
        ),
    ]
