# Generated by Django 6.0.8 on 2026-09-22 08:16

import common.money.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nazwa widoczna dla klienta, np. „Paczkomat InPost”",
                        max_length=120,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("parcel_locker", "Paczkomat"),
                            ("courier", "Kurier"),
                            ("pickup", "Odbiór osobisty"),
                            ("eu", "Przesyłka do Unii"),
                        ],
                        help_text="Sposób dostarczenia",
                        max_length=16,
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[("PL", "Polska"), ("EU", "Unia Europejska")],
                        default="PL",
                        help_text="Strefa, dla której obowiązuje stawka",
                        max_length=2,
                    ),
                ),
                (
                    "rate",
                    common.money.fields.MoneyAmountField(
                        help_text="Stawka brutto w groszach; ubezpieczenie jest w niej zawarte",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    common.money.fields.CurrencyField(
                        default="PLN",
                        help_text="Kod waluty ISO 4217",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$",
                                "Kod waluty to trzy wielkie litery ISO 4217",
                            )
                        ],
                    ),
                ),
                (
                    "max_order_value",
                    common.money.fields.MoneyAmountField(
                        blank=True,
                        help_text="Górna wartość zamówienia w groszach, powyżej której metoda jest niedostępna. Puste oznacza brak limitu.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Metoda wygaszona nie wychodzi przez API i nie da się jej wybrać",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metoda dostawy",
                "verbose_name_plural": "Metody dostawy",
                "ordering": ["zone", "rate", "name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rate__gte", 0)),
                        name="shipping_method_rate_is_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_order_value__isnull", True),
                            ("max_order_value__gte", 0),
                            _connector="OR",
                        ),
                        name="shipping_method_max_order_value_is_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "pickup"), _negated=True),
                            ("max_order_value__isnull", True),
                            _connector="OR",
                        ),
                        name="shipping_method_pickup_has_no_value_limit",
                    ),
                ],
            },
        ),
    ]
