# Generated by Django 6.0.8 on 2026-09-22 18:21

import common.money.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_orderitem_order_order_email_lower_idx_and_more"),
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        help_text="Numer śledzenia u przewoźnika; pusty do chwili nadania",
                        max_length=64,
                    ),
                ),
                (
                    "declared_value",
                    common.money.fields.MoneyAmountField(
                        help_text="Wartość zadeklarowana przewoźnikowi w groszach. Nie wychodzi przez API — ubezpieczenie jest wliczone w stawkę (ADR 0028).",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    common.money.fields.CurrencyField(
                        default="PLN",
                        help_text="Kod waluty ISO 4217",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$",
                                "Kod waluty to trzy wielkie litery ISO 4217",
                            )
                        ],
                    ),
                ),
                (
                    "pickup_point_code",
                    models.CharField(
                        blank=True,
                        help_text="Kod punktu odbioru; wypełniany wyłącznie dla paczkomatu",
                        max_length=32,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Zamówienie, w ramach którego idzie przesyłka",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Przesyłka",
                "verbose_name_plural": "Przesyłki",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("declared_value__gte", 0)),
                        name="shipment_declared_value_is_not_negative",
                    )
                ],
            },
        ),
    ]
