# Generated by Django 6.0.8 on 2026-09-20 01:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "products",
            "0002_costcomponent_metalrate_productvariant_margin_amount_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "reserved",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ilość wyłączona z dostępności na czas płatności. Prowadzi ją zamówienie — `Reservation` nie należy do magazynu.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stan magazynowy",
                "verbose_name_plural": "Stany magazynowe",
                "ordering": ["variant__sku"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Zmiana stanu; ujemna zdejmuje ze stanu"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("delivery", "Dostawa"),
                            ("sale", "Sprzedaż"),
                            ("return", "Zwrot"),
                            ("correction", "Korekta inwentaryzacyjna"),
                            ("loss", "Ubytek"),
                        ],
                        help_text="Przyczyna ruchu",
                        max_length=16,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Uzupełnienie przyczyny, np. numer dostawy",
                        max_length=200,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ruch magazynowy",
                "verbose_name_plural": "Ruchy magazynowe",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity", 0), _negated=True),
                        name="stock_movement_quantity_is_not_zero",
                    )
                ],
            },
        ),
    ]
