# Generated by Django 6.0.8 on 2026-09-22 10:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        ("products", "0006_product_engraving"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="reserved",
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        help_text="Liczba sztuk wyłączona z dostępności",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Chwila, po której rezerwacja przestaje trzymać stan"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktywna"),
                            ("released", "Zwolniona"),
                            ("consumed", "Rozliczona"),
                        ],
                        default="active",
                        help_text="Aktywna trzyma stan; zwolniona i rozliczona już nie",
                        max_length=16,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        help_text="Wariant, którego ilość jest wyłączona z dostępności",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezerwacja",
                "verbose_name_plural": "Rezerwacje",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"],
                        name="inventory_r_status_8d1db9_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 1)),
                        name="reservation_quantity_is_positive",
                    )
                ],
            },
        ),
    ]
