# Generated by Django 6.0.8 on 2026-09-22 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_remove_inventoryitem_reserved_reservation"),
        ("orders", "0002_order_orderitem_order_order_email_lower_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="Zamówienie, które trzyma ten stan. Puste tylko dla rezerwacji założonej poza kasą — w normalnym przepływie zawsze wypełnione.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="orders.order",
            ),
        ),
    ]
