# Generated by Django 6.0.8 on 2026-09-22 04:47

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("terms", "Regulamin"),
                            ("privacy", "Polityka prywatności"),
                            ("marketing", "Komunikacja marketingowa"),
                        ],
                        help_text="Rodzaj dokumentu",
                        max_length=16,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Oznaczenie wersji, np. 2026-09; unikalne w obrębie rodzaju",
                        max_length=32,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        help_text="Dzień, od którego wersja obowiązuje. Najnowsza obowiązująca wersja jest bieżącą; wcześniejsze zgody przestają być aktualne."
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument zgody",
                "verbose_name_plural": "Dokumenty zgód",
                "ordering": ["kind", "-effective_from", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "version"),
                        name="consent_document_version_unique_per_kind",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="E-mail gościa bez konta; pusty przy zgodzie zalogowanego",
                        max_length=254,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        editable=False,
                        help_text="Kopia wersji dokumentu z chwili udzielenia zgody",
                        max_length=32,
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Chwila udzielenia zgody",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Zalogowany klient, który udzielił zgody",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Wersja dokumentu, której dotyczy zgoda",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consents",
                        to="consents.consentdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zgoda",
                "verbose_name_plural": "Zgody",
                "ordering": ["-granted_at", "-id"],
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("email"),
                        name="consent_email_lower_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("email", ""), ("user__isnull", False)),
                            models.Q(
                                ("user__isnull", True),
                                models.Q(("email", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="consent_subject_is_user_xor_email",
                    )
                ],
            },
        ),
    ]
