# Generated by Django 6.0.8 on 2026-09-22 20:15

import common.money.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0002_order_orderitem_order_order_email_lower_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                (
                    "kind",
                    models.CharField(
                        help_text="Rodzaj zdarzenia w nazewnictwie operatora",
                        max_length=64,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Zdarzenie operatora",
                "verbose_name_plural": "Zdarzenia operatora",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "intent_id",
                    models.CharField(
                        help_text="Identyfikator intencji płatniczej u operatora",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    common.money.fields.MoneyAmountField(
                        help_text="Kwota intencji w groszach",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "currency",
                    common.money.fields.CurrencyField(
                        default="PLN",
                        help_text="Kod waluty ISO 4217",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$",
                                "Kod waluty to trzy wielkie litery ISO 4217",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje na operatora"),
                            ("succeeded", "Zapłacona"),
                            ("failed", "Nieudana"),
                            ("refunding", "Zwrot w toku"),
                            ("refunded", "Zwrócona"),
                            ("refund_failed", "Zwrot odrzucony"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "refund_id",
                    models.CharField(
                        blank=True,
                        help_text="Identyfikator zwrotu u operatora",
                        max_length=255,
                    ),
                ),
                (
                    "refund_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cancellation", "Anulowanie przez klienta"),
                            ("out_of_stock", "Towar zszedł przed rozliczeniem"),
                            ("order_closed", "Zamówienie nie czekało już na zapłatę"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Płatność",
                "verbose_name_plural": "Płatności",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="payment_amount_is_positive",
                    )
                ],
            },
        ),
    ]
