# Generated by Django 6.0.8 on 2026-09-24 03:34

import common.money.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("collections", "0001_initial"),
        ("orders", "0003_sales_document"),
        ("products", "0006_product_engraving"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nazwa promocji po polsku", max_length=120
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("percent", "Procentowa"), ("amount", "Kwotowa")],
                        help_text="Procentowa albo kwotowa",
                        max_length=16,
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        help_text="Procent obniżki (1–100) albo kwota obniżki jednego egzemplarza w groszach — zależnie od rodzaju",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "currency",
                    common.money.fields.CurrencyField(
                        default="PLN",
                        help_text="Waluta kwoty obniżki i minimalnej wartości koszyka",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$",
                                "Kod waluty to trzy wielkie litery ISO 4217",
                            )
                        ],
                    ),
                ),
                (
                    "whole_catalog",
                    models.BooleanField(
                        default=False,
                        help_text="Promocja na cały katalog — wtedy listy poniżej są pomijane",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Początek obowiązywania",
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Koniec obowiązywania; puste oznacza promocję bezterminową",
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Kod aktywujący promocję w koszyku; puste oznacza promocję działającą bez kodu. Wielkość liter nie ma znaczenia.",
                        max_length=32,
                    ),
                ),
                (
                    "requires_premium",
                    models.BooleanField(
                        default=False,
                        help_text="Tylko dla klientów premium. Do czasu wprowadzenia członkostwa taka promocja nie działa dla nikogo.",
                    ),
                ),
                (
                    "per_customer_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ile zamówień jednego klienta może z niej skorzystać; puste — bez limitu",
                        null=True,
                    ),
                ),
                (
                    "global_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ile zamówień łącznie może z niej skorzystać; puste — bez limitu",
                        null=True,
                    ),
                ),
                (
                    "min_cart_value",
                    common.money.fields.MoneyAmountField(
                        blank=True,
                        help_text="Minimalna wartość koszyka w groszach, przed rabatami",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Kategorie objęte promocją — razem z ich podkategoriami",
                        related_name="promotions",
                        to="categories.category",
                    ),
                ),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Kolekcje objęte promocją",
                        related_name="promotions",
                        to="collections.collection",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Produkty objęte promocją",
                        related_name="promotions",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promocja",
                "verbose_name_plural": "Promocje",
                "ordering": ["-starts_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PromotionRedemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "amount",
                    common.money.fields.MoneyAmountField(
                        help_text="Suma rabatu tej promocji w zamówieniu, w walucie zamówienia",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_redemptions",
                        to="orders.order",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zastosowanie promocji",
                "verbose_name_plural": "Zastosowania promocji",
            },
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("code",),
                name="promotion_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("value__gte", 1),
                    models.Q(
                        models.Q(("kind", "percent"), _negated=True),
                        ("value__lte", 100),
                        _connector="OR",
                    ),
                ),
                name="promotion_value_within_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_at__isnull", True),
                    ("ends_at__gt", models.F("starts_at")),
                    _connector="OR",
                ),
                name="promotion_ends_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionredemption",
            constraint=models.UniqueConstraint(
                fields=("promotion", "order"),
                name="promotion_redemption_unique_per_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionredemption",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="promotion_redemption_amount_is_not_negative",
            ),
        ),
    ]
