# Generated by Django 6.0.8 on 2026-09-24 18:55

import apps.promotions.models
import common.money.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.math
import django.db.models.lookups
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_cart_promotion"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=apps.promotions.models.new_coupon_code,
                        help_text="Kod nadany przez sklep. Wielkość liter nie ma znaczenia.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "nominal",
                    common.money.fields.MoneyAmountField(
                        help_text="Nominał w groszach — wielokrotność 10 zł (1000 gr)",
                        validators=[apps.promotions.models._validate_nominal],
                    ),
                ),
                (
                    "currency",
                    common.money.fields.CurrencyField(
                        default="PLN",
                        help_text="Waluta nominału",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$",
                                "Kod waluty to trzy wielkie litery ISO 4217",
                            )
                        ],
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.promotions.models.twelve_months_later,
                        help_text="Koniec ważności — 12 miesięcy od wydania",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Wydany"),
                            ("redeemed", "Wykorzystany"),
                            ("expired", "Wygasły"),
                        ],
                        default="issued",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("campaign", "Kampania"), ("return", "Zwrot")],
                        default="campaign",
                        help_text="Skąd kupon: kampania marketingowa albo przyjęty zwrot",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kupon",
                "verbose_name_plural": "Kupony",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            django.db.models.lookups.Exact(
                                django.db.models.functions.math.Mod("nominal", 1000), 0
                            ),
                            ("nominal__gt", 0),
                        ),
                        name="coupon_nominal_multiple_of_ten_zloty",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CouponRedemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "amount",
                    common.money.fields.MoneyAmountField(
                        help_text="Kwota pokryta kuponem — najwyżej nominał, reszta przepada",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="promotions.coupon",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_redemption",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Użycie kuponu",
                "verbose_name_plural": "Użycia kuponów",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="coupon_redemption_amount_is_not_negative",
                    )
                ],
            },
        ),
    ]
