# Generated by Django 6.0.8 on 2026-09-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0002_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="requires_premium",
            field=models.BooleanField(
                default=False,
                help_text="Tylko dla klientów premium (`CONTEXT.md`, Membership).",
            ),
        ),
    ]
