# Generated by Django 6.0.8 on 2026-09-25 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_return_settlement"),
        ("promotions", "0003_alter_promotion_requires_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="source_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Zamówienie, którego zwrot wydał kupon (ADR 0014)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="return_coupons",
                to="orders.order",
            ),
        ),
    ]
