# Generated by Django 6.0.8 on 2026-09-19 15:51

import common.money.fields
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nazwa produktu po polsku", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Opis produktu po polsku"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Angielski identyfikator w adresie. Puste pole zostanie wypełnione z nazwy przy zapisie. Po publikacji nie da się go zmienić.",
                        max_length=140,
                        unique=True,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("gold", "Złoto"),
                            ("silver", "Srebro"),
                            ("platinum", "Platyna"),
                            ("palladium", "Pallad"),
                        ],
                        help_text="Kruszec, z którego wykonany jest wyrób",
                        max_length=16,
                    ),
                ),
                (
                    "fineness",
                    models.CharField(
                        choices=[
                            ("333", "333 (8 karatów)"),
                            ("375", "375 (9 karatów)"),
                            ("585", "585 (14 karatów)"),
                            ("750", "750 (18 karatów)"),
                            ("916", "916 (22 karaty)"),
                            ("925", "925 (srebro próby 925)"),
                            ("950", "950 (platyna)"),
                            ("999", "999 (kruszec inwestycyjny)"),
                        ],
                        help_text="Próba kruszcu",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Szkic"), ("published", "Opublikowany")],
                        default="draft",
                        help_text="Tylko produkt opublikowany jest widoczny w sklepie",
                        max_length=16,
                    ),
                ),
                (
                    "is_made_to_order",
                    models.BooleanField(
                        default=False,
                        help_text="Wyrób wytwarzany po złożeniu zamówienia (ADR 0024). Nie ma stanu magazynowego, ma za to czas realizacji.",
                    ),
                ),
                (
                    "production_time_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Czas realizacji w dniach; wymagany przy produkcie na zamówienie",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Kategoria-liść, czyli węzeł bez podkategorii",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produkt",
                "verbose_name_plural": "Produkty",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Oznaczenie magazynowe wariantu, unikalne w całym katalogu",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "metal_color",
                    models.CharField(
                        choices=[
                            ("yellow", "Żółte"),
                            ("white", "Białe"),
                            ("rose", "Różowe"),
                            ("bicolor", "Dwukolorowe"),
                        ],
                        help_text="Kolor kruszcu",
                        max_length=16,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                            ("16", "16"),
                            ("17", "17"),
                            ("18", "18"),
                            ("19", "19"),
                            ("20", "20"),
                            ("21", "21"),
                            ("22", "22"),
                            ("23", "23"),
                            ("24", "24"),
                            ("25", "25"),
                            ("26", "26"),
                        ],
                        help_text="Rozmiar pierścionka; puste dla wyrobów bez rozmiaru",
                        max_length=2,
                    ),
                ),
                (
                    "length",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("16", "16 cm"),
                            ("18", "18 cm"),
                            ("20", "20 cm"),
                            ("36", "36 cm"),
                            ("38", "38 cm"),
                            ("40", "40 cm"),
                            ("42", "42 cm"),
                            ("45", "45 cm"),
                            ("50", "50 cm"),
                            ("55", "55 cm"),
                            ("60", "60 cm"),
                            ("70", "70 cm"),
                            ("80", "80 cm"),
                        ],
                        help_text="Długość w centymetrach; puste dla wyrobów bez długości",
                        max_length=2,
                    ),
                ),
                (
                    "stone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("diamond", "Diament"),
                            ("sapphire", "Szafir"),
                            ("ruby", "Rubin"),
                            ("emerald", "Szmaragd"),
                            ("pearl", "Perła"),
                            ("amber", "Bursztyn"),
                            ("topaz", "Topaz"),
                            ("amethyst", "Ametyst"),
                            ("cubic_zirconia", "Cyrkonia"),
                            ("moissanite", "Moissanit"),
                        ],
                        help_text="Rodzaj kamienia; puste dla wyrobu bez kamienia",
                        max_length=16,
                    ),
                ),
                (
                    "metal_weight_grams",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Masa kruszcu w gramach — podstawa składnika kruszcowego ceny",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "price",
                    common.money.fields.MoneyAmountField(
                        help_text="Cena brutto w groszach, wyliczona ze wzoru (ADR 0022)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "manual_price",
                    common.money.fields.MoneyAmountField(
                        blank=True,
                        help_text="Cena brutto wpisana ręcznie; ma pierwszeństwo przed wyliczoną. Służy wyprzedaży, nie codziennej wycenie.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    common.money.fields.CurrencyField(
                        default="PLN",
                        help_text="Kod waluty ISO 4217",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$",
                                "Kod waluty to trzy wielkie litery ISO 4217",
                            )
                        ],
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Stawka podatku jako ułamek, np. 0.2300. Pusta wyłącznie przy zwolnieniu.",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "is_vat_exempt",
                    models.BooleanField(
                        default=False,
                        help_text="Zwolnienie przedmiotowe — złoto inwestycyjne. Nie jest stawką zerową, tylko osobnym bytem (ADR 0013).",
                    ),
                ),
                (
                    "vat_exemption_basis",
                    models.CharField(
                        blank=True,
                        help_text="Podstawa prawna zwolnienia; wymagana przy zwolnieniu",
                        max_length=200,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wariant produktu",
                "verbose_name_plural": "Warianty produktu",
                "ordering": ["sku"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["status"], name="products_pr_status_041708_idx"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_made_to_order", True),
                        ("production_time_days__isnull", False),
                    ),
                    models.Q(
                        ("is_made_to_order", False),
                        ("production_time_days__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="product_made_to_order_has_production_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_vat_exempt", True), ("vat_rate__isnull", True)),
                    models.Q(("is_vat_exempt", False), ("vat_rate__isnull", False)),
                    _connector="OR",
                ),
                name="variant_exemption_excludes_vat_rate",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_vat_exempt", False),
                    models.Q(("vat_exemption_basis", ""), _negated=True),
                    _connector="OR",
                ),
                name="variant_exemption_has_legal_basis",
            ),
        ),
    ]
