# Generated by Django 6.0.8 on 2026-09-20 01:34

import common.money.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nazwa pozycji kosztu, np. robocizna, rodowanie, oprawa",
                        max_length=80,
                    ),
                ),
                (
                    "amount",
                    common.money.fields.MoneyAmountField(
                        help_text="Kwota w groszach",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    common.money.fields.CurrencyField(
                        default="PLN",
                        help_text="Kod waluty ISO 4217",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$",
                                "Kod waluty to trzy wielkie litery ISO 4217",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Składnik kosztu",
                "verbose_name_plural": "Składniki kosztu",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="MetalRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "metal",
                    models.CharField(
                        choices=[
                            ("gold", "Złoto"),
                            ("silver", "Srebro"),
                            ("platinum", "Platyna"),
                            ("palladium", "Pallad"),
                        ],
                        help_text="Kruszec, którego dotyczy kurs",
                        max_length=16,
                    ),
                ),
                (
                    "fineness",
                    models.CharField(
                        choices=[
                            ("333", "333 (8 karatów)"),
                            ("375", "375 (9 karatów)"),
                            ("585", "585 (14 karatów)"),
                            ("750", "750 (18 karatów)"),
                            ("916", "916 (22 karaty)"),
                            ("925", "925 (srebro próby 925)"),
                            ("950", "950 (platyna)"),
                            ("999", "999 (kruszec inwestycyjny)"),
                        ],
                        help_text="Próba kruszcu — kurs za gram zależy od zawartości metalu",
                        max_length=3,
                    ),
                ),
                (
                    "price_per_gram",
                    common.money.fields.MoneyAmountField(
                        help_text="Cena za gram w groszach",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "currency",
                    common.money.fields.CurrencyField(
                        default="PLN",
                        help_text="Kod waluty ISO 4217",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$",
                                "Kod waluty to trzy wielkie litery ISO 4217",
                            )
                        ],
                    ),
                ),
                (
                    "quoted_on",
                    models.DateField(help_text="Dzień, z którego pochodzi notowanie"),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Skąd pochodzi kurs — jedyne miejsce, w którym pada nazwa dostawcy",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Zaproponowany"),
                            ("active", "Aktywny"),
                            ("archived", "Zarchiwizowany"),
                        ],
                        default="proposed",
                        help_text="Tylko kurs aktywny wpływa na ceny wariantów",
                        max_length=16,
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Chwila aktywacji; puste dopóki kurs nie został zatwierdzony",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs kruszcu",
                "verbose_name_plural": "Kursy kruszców",
                "ordering": ["-quoted_on", "-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="productvariant",
            name="margin_amount",
            field=common.money.fields.MoneyAmountField(
                blank=True,
                help_text="Narzut kwotowy w groszach nadpisujący narzut kategorii. Wyklucza się z narzutem procentowym.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="margin_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Narzut procentowy nadpisujący narzut kategorii (ADR 0022). Pusty oznacza narzut odziedziczony.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("margin_percent__isnull", True),
                    ("margin_amount__isnull", True),
                    _connector="OR",
                ),
                name="variant_margin_is_percent_or_amount",
            ),
        ),
        migrations.AddField(
            model_name="costcomponent",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_components",
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="metalrate",
            name="activated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Kto zatwierdził kurs — zostaje w dzienniku zmian",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activated_metal_rates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="costcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="cost_component_amount_is_not_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="metalrate",
            index=models.Index(
                fields=["metal", "fineness", "status"],
                name="products_me_metal_0b72e8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="metalrate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("metal", "fineness"),
                name="metal_rate_single_active_per_metal_and_fineness",
            ),
        ),
        migrations.AddConstraint(
            model_name="metalrate",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_per_gram__gt", 0)),
                name="metal_rate_price_is_positive",
            ),
        ),
    ]
