# Generated by Django 6.0.8 on 2026-09-20 01:56

import apps.products.models.image
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0002_costcomponent_metalrate_productvariant_margin_amount_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Kolejność w galerii; mniejsza liczba wcześniej",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Zdjęcie główne produktu — jedno na produkt",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Opis alternatywny po polsku, dla czytników ekranu i SEO",
                        max_length=200,
                    ),
                ),
                (
                    "original",
                    models.FileField(
                        help_text="Oryginał zdjęcia, najwyżej 10 MB. Zostaje zachowany, żeby zmiana kadru nie wymagała ponownego wgrania.",
                        storage=apps.products.models.image.originals_storage,
                        upload_to="uploads/",
                        validators=[apps.products.models.image.validate_original_size],
                    ),
                ),
                (
                    "crop",
                    models.JSONField(
                        blank=True,
                        help_text='Prostokąt kadru względem oryginału: {"x": 0, "y": 0, "width": 1000, "height": 1000}. Puste oznacza całe zdjęcie.',
                        null=True,
                    ),
                ),
                (
                    "renditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        editable=False,
                        help_text="Klucze gotowych rozmiarów w buckecie publicznym",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "W przetwarzaniu"),
                            ("ready", "Gotowe"),
                        ],
                        default="processing",
                        editable=False,
                        help_text="Zdjęcie w przetwarzaniu nie wychodzi przez API",
                        max_length=16,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Wariant, którego wygląd zdjęcie różnicuje. Puste oznacza zdjęcie całego produktu.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zdjęcie produktu",
                "verbose_name_plural": "Zdjęcia produktu",
                "ordering": ["position", "created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["product", "status"],
                        name="products_pr_product_509539_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("product",),
                        name="product_image_single_primary_per_product",
                    )
                ],
            },
        ),
    ]
