# Generated by Django 6.0.8 on 2026-09-20 02:09

import apps.products.models.gemstone
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_productimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gemstone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("diamond", "Diament"),
                            ("sapphire", "Szafir"),
                            ("ruby", "Rubin"),
                            ("emerald", "Szmaragd"),
                            ("pearl", "Perła"),
                            ("amber", "Bursztyn"),
                            ("topaz", "Topaz"),
                            ("amethyst", "Ametyst"),
                            ("cubic_zirconia", "Cyrkonia"),
                            ("moissanite", "Moissanit"),
                        ],
                        help_text="Rodzaj kamienia",
                        max_length=16,
                    ),
                ),
                (
                    "carat",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Masa w karatach",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "clarity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FL", "FL — bez skaz"),
                            ("IF", "IF — bez skaz wewnętrznych"),
                            ("VVS1", "VVS1"),
                            ("VVS2", "VVS2"),
                            ("VS1", "VS1"),
                            ("VS2", "VS2"),
                            ("SI1", "SI1"),
                            ("SI2", "SI2"),
                            ("I1", "I1"),
                            ("I2", "I2"),
                            ("I3", "I3"),
                        ],
                        help_text="Czystość; pusta, gdy nie była oznaczana",
                        max_length=4,
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("D", "D — bezbarwny"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                            ("K", "K"),
                            ("L", "L"),
                            ("M", "M"),
                            ("fancy", "Barwa fantazyjna"),
                        ],
                        help_text="Barwa; pusta, gdy nie była oznaczana",
                        max_length=8,
                    ),
                ),
                (
                    "cut",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("brilliant", "Brylantowy"),
                            ("princess", "Princessa"),
                            ("emerald", "Szmaragdowy"),
                            ("oval", "Owalny"),
                            ("pear", "Gruszka"),
                            ("marquise", "Markiza"),
                            ("cushion", "Poduszka"),
                            ("asscher", "Asscher"),
                            ("radiant", "Radiant"),
                            ("heart", "Serce"),
                            ("cabochon", "Kaboszon"),
                        ],
                        help_text="Szlif; pusty, gdy nie był oznaczany",
                        max_length=16,
                    ),
                ),
                (
                    "laboratory",
                    models.CharField(
                        blank=True,
                        help_text="Laboratorium, które wystawiło certyfikat",
                        max_length=80,
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True,
                        help_text="Numer certyfikatu nadany przez laboratorium",
                        max_length=64,
                    ),
                ),
                (
                    "certificate",
                    models.FileField(
                        blank=True,
                        help_text="PDF certyfikatu. Trafia do prywatnego bucketa `documents` — klient dostaje adres podpisany na czas, nie stały odnośnik.",
                        storage=apps.products.models.gemstone.documents_storage,
                        upload_to="certificates/",
                        validators=[apps.products.models.gemstone.validate_certificate],
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gemstones",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kamień",
                "verbose_name_plural": "Kamienie",
                "ordering": ["-carat", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("carat__gt", 0)),
                        name="gemstone_carat_is_positive",
                    )
                ],
            },
        ),
    ]
