# Generated by Django 6.0.8 on 2026-09-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_gemstone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Angielski identyfikator w adresie. Puste pole zostanie wypełnione z angielskiego brzmienia nazwy przy publikacji. Po publikacji nie da się go zmienić.",
                max_length=140,
                null=True,
                unique=True,
            ),
        ),
    ]
