# Generated by Django 6.0.8 on 2026-09-22 04:37

import common.money.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("products", "0005_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="engraving_price",
            field=common.money.fields.MoneyAmountField(
                blank=True,
                help_text="Cena grawerunku brutto w groszach (PLN); wymagana przy produkcie grawerowalnym",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_engravable",
            field=models.BooleanField(
                default=False,
                help_text="Wyrób można grawerować (ADR 0018). Grawer jest osobną pozycją ceny doliczaną do wariantu i wyłącza prawo odstąpienia.",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("engraving_price__isnull", False), ("is_engravable", True)
                    ),
                    models.Q(
                        ("engraving_price__isnull", True), ("is_engravable", False)
                    ),
                    _connector="OR",
                ),
                name="product_engravable_has_engraving_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("engraving_price__isnull", True),
                    ("engraving_price__gte", 0),
                    _connector="OR",
                ),
                name="product_engraving_price_is_not_negative",
            ),
        ),
    ]
