# Generated by Django 6.0.8 on 2026-09-25 00:37

import common.money.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_product_engraving"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "base_currency",
                    common.money.fields.CurrencyField(
                        default="PLN",
                        help_text="Waluta cen źródłowych",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$",
                                "Kod waluty to trzy wielkie litery ISO 4217",
                            )
                        ],
                    ),
                ),
                (
                    "currency",
                    common.money.fields.CurrencyField(
                        default="EUR",
                        help_text="Waluta, na którą przeliczamy",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$",
                                "Kod waluty to trzy wielkie litery ISO 4217",
                            )
                        ],
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Ile jednostek waluty bazowej kosztuje jedna jednostka waluty",
                        max_digits=12,
                    ),
                ),
                (
                    "effective_on",
                    models.DateField(help_text="Dzień, z którego pochodzi notowanie"),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Skąd pochodzi kurs — jedyne miejsce, w którym pada nazwa dostawcy",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs waluty",
                "verbose_name_plural": "Kursy walut",
                "ordering": ["-effective_on", "-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("base_currency", "currency", "effective_on"),
                        name="exchange_rate_single_per_pair_and_day",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rate__gt", 0)),
                        name="exchange_rate_is_positive",
                    ),
                ],
            },
        ),
    ]
