# Generated by Django 6.0.8 on 2026-09-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_exchange_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="repair_available",
            field=models.BooleanField(
                default=False,
                help_text="Reklamację wyrobu można załatwić naprawą (`CONTEXT.md`, ReturnReason)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="replacement_available",
            field=models.BooleanField(
                default=False,
                help_text="Reklamację wyrobu można załatwić wymianą (`CONTEXT.md`, ReturnReason)",
            ),
        ),
    ]
