# Generated by Django 6.0.8 on 2026-09-19 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nazwa kolekcji po polsku, widoczna w sklepie",
                        max_length=120,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Opis kampanii albo sezonu po polsku"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Angielski identyfikator w adresie. Puste pole zostanie wypełnione z nazwy przy zapisie. Po zapisaniu nie da się go zmienić.",
                        max_length=140,
                        unique=True,
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Produkty przypięte do kolekcji; mogą być z różnych kategorii",
                        related_name="collections",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kolekcja",
                "verbose_name_plural": "Kolekcje",
                "ordering": ["name", "id"],
            },
        ),
    ]
