# Generated by Django 6.0.8 on 2026-09-19 15:28

import common.money.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nazwa kategorii po polsku, widoczna w menu sklepu",
                        max_length=120,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Angielski identyfikator w adresie. Puste pole zostanie wypełnione z nazwy przy zapisie. Po zapisaniu nie da się go zmienić.",
                        max_length=140,
                        unique=True,
                    ),
                ),
                (
                    "margin_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Domyślny narzut procentowy dla wariantów w tej kategorii (ADR 0022). Wyklucza się z narzutem kwotowym.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "margin_amount",
                    common.money.fields.MoneyAmountField(
                        blank=True,
                        help_text="Domyślny narzut kwotowy w groszach (PLN). Wyklucza się z narzutem procentowym.",
                        null=True,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kategoria nadrzędna; puste oznacza korzeń drzewa",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoria",
                "verbose_name_plural": "Kategorie",
                "ordering": ["name", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("margin_percent__isnull", True),
                            ("margin_amount__isnull", True),
                            _connector="OR",
                        ),
                        name="category_margin_is_percent_or_amount",
                    )
                ],
            },
        ),
    ]
