# Generated by Django 6.0.8 on 2026-09-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("order_status_changed", "Zmiana statusu zamówienia"),
                    ("order_paid", "Zamówienie opłacone"),
                    ("document_ready", "Dokument gotowy"),
                    ("return_request_status_changed", "Zmiana stanu zgłoszenia zwrotu"),
                ],
                help_text="Rodzaj zdarzenia",
                max_length=32,
            ),
        ),
    ]
