# Generated by Django 6.0.8 on 2026-09-28 19:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_notification_kind_return_settled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Token push Expo (ExponentPushToken[...])",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")],
                        help_text="Platforma urządzenia",
                        max_length=16,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Ostatnia rejestracja lub wysyłka na to urządzenie",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Klient, do którego należy urządzenie",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Urządzenie push",
                "verbose_name_plural": "Urządzenia push",
                "ordering": ["-last_used_at", "-id"],
            },
        ),
    ]
