# Generated by Django 6.0.8 on 2026-10-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_newsletter_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("order_status_changed", "Zmiana statusu zamówienia"),
                    ("order_paid", "Zamówienie opłacone"),
                    ("document_ready", "Dokument gotowy"),
                    ("return_request_status_changed", "Zmiana stanu zgłoszenia zwrotu"),
                    ("return_settled", "Rozliczenie zwrotu"),
                    ("watch_restock", "Wariant wrócił na stan"),
                    ("watch_price_drop", "Spadek ceny wariantu"),
                    ("cart_reminder", "Przypomnienie o koszyku"),
                ],
                help_text="Rodzaj zdarzenia",
                max_length=32,
            ),
        ),
    ]
