# Generated by Django 6.0.8 on 2026-09-20 02:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "field",
                    models.CharField(
                        help_text="Nazwa pola modelu, którego dotyczy tłumaczenie",
                        max_length=64,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "angielski")],
                        default="en",
                        help_text="Język docelowy; polski jest źródłem i nie ma tu wpisów",
                        max_length=8,
                    ),
                ),
                ("text", models.TextField(help_text="Przetłumaczony tekst")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("auto", "Automatyczne"),
                            ("manual", "Poprawione ręcznie"),
                        ],
                        default="auto",
                        help_text="Automat czy poprawka właściciela",
                        max_length=8,
                    ),
                ),
                (
                    "translated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Kiedy powstało to brzmienie",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tłumaczenie",
                "verbose_name_plural": "Tłumaczenia",
                "ordering": ["content_type", "object_id", "field", "language"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "language"],
                        name="translation_content_4d2748_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "field", "language"),
                        name="translation_one_per_field_and_language",
                    )
                ],
            },
        ),
    ]
