# Generated by Django 6.0.8 on 2026-09-22 09:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0006_product_engraving"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Token koszyka gościa wydany przez backend i odsyłany nagłówkiem `X-Cart-Token`; pusty przy koszyku konta",
                        max_length=64,
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Ostatnia zmiana w koszyku. Koszyk gościa bez aktywności przez 30 dni jest kasowany zadaniem okresowym.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Zalogowany właściciel koszyka; pusty przy koszyku gościa",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Koszyk",
                "verbose_name_plural": "Koszyki",
                "ordering": ["-last_activity_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Liczba sztuk pozycji, najwyżej 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "engraving_text",
                    models.CharField(
                        blank=True,
                        help_text="Treść grawerunku; przy parze trafia na oba egzemplarze, o ile drugi nie ma własnej. Puste oznacza wyrób bez grawerunku.",
                        max_length=50,
                    ),
                ),
                (
                    "second_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                            ("16", "16"),
                            ("17", "17"),
                            ("18", "18"),
                            ("19", "19"),
                            ("20", "20"),
                            ("21", "21"),
                            ("22", "22"),
                            ("23", "23"),
                            ("24", "24"),
                            ("25", "25"),
                            ("26", "26"),
                        ],
                        help_text="Rozmiar drugiego egzemplarza pary. Wypełniony zamienia pozycję w parę; pierwszy rozmiar bierze się z wariantu.",
                        max_length=2,
                    ),
                ),
                (
                    "second_engraving_text",
                    models.CharField(
                        blank=True,
                        help_text="Grawerunek drugiego egzemplarza, gdy ma być inny niż pierwszego",
                        max_length=50,
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.cart",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        help_text="Kupowany wariant — jedyna rzecz, którą da się dodać do koszyka",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cart_items",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pozycja koszyka",
                "verbose_name_plural": "Pozycje koszyka",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("session_key", ""), ("user__isnull", False)),
                    models.Q(
                        ("user__isnull", True),
                        models.Q(("session_key", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="cart_owner_is_user_xor_session_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key", ""), _negated=True),
                fields=("session_key",),
                name="cart_session_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=(
                    "cart",
                    "variant",
                    "engraving_text",
                    "second_size",
                    "second_engraving_text",
                ),
                name="cart_item_unique_per_personalisation",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1), ("quantity__lte", 5)),
                name="cart_item_quantity_within_limit",
            ),
        ),
    ]
