# Generated by Django 6.0.8 on 2026-09-22 18:21

import apps.orders.models.order
import common.money.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consents", "0001_initial"),
        ("orders", "0001_initial"),
        ("products", "0006_product_engraving"),
        ("shipping", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        default=apps.orders.models.order.new_order_number,
                        editable=False,
                        help_text="Numer, którym klient posługuje się w kontakcie ze sklepem",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Adres, pod który idzie potwierdzenie. Zawsze wypełniony — także dla klienta z kontem, bo zamówienie ma zostać czytelne po anonimizacji konta.",
                        max_length=254,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje na zapłatę"),
                            ("paid", "Opłacone"),
                            ("in_production", "W produkcji"),
                            ("packed", "Spakowane"),
                            ("shipped", "Wysłane"),
                            ("delivered", "Dostarczone"),
                            ("cancelled", "Anulowane"),
                            ("returned", "Zwrócone"),
                        ],
                        default="pending",
                        help_text="Etap cyklu życia zamówienia",
                        max_length=16,
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        help_text="Imię i nazwisko odbiorcy z chwili złożenia zamówienia",
                        max_length=200,
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("street2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "country",
                    models.CharField(
                        help_text="Kod kraju ISO 3166-1 alfa-2 z chwili złożenia zamówienia",
                        max_length=2,
                    ),
                ),
                (
                    "shipping_method_name",
                    models.CharField(
                        help_text="Nazwa metody z chwili złożenia — cennik wolno potem zmienić",
                        max_length=120,
                    ),
                ),
                (
                    "shipping_cost",
                    common.money.fields.MoneyAmountField(
                        help_text="Koszt dostawy w groszach, zamrożony przy składaniu zamówienia",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    common.money.fields.CurrencyField(
                        default="PLN",
                        help_text="Kod waluty ISO 4217",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$",
                                "Kod waluty to trzy wielkie litery ISO 4217",
                            )
                        ],
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        help_text="Kurs, po którym przeliczono ceny źródłowe na walutę zamówienia. Jeden przy sprzedaży w złotych (ADR 0019).",
                        max_digits=12,
                    ),
                ),
                (
                    "discount_amount",
                    common.money.fields.MoneyAmountField(
                        default=0,
                        help_text="Suma rabatów z promocji; wypełni ją bilet promocji",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "coupon_amount",
                    common.money.fields.MoneyAmountField(
                        default=0,
                        help_text="Kwota pokryta kuponem; wypełni ją bilet kuponów",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "terms_version",
                    models.CharField(
                        editable=False,
                        help_text="Kopia oznaczenia wersji regulaminu z chwili złożenia",
                        max_length=32,
                    ),
                ),
                (
                    "shipping_method",
                    models.ForeignKey(
                        help_text="Wybrana metoda dostawy; kwota i nazwa są skopiowane obok",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="shipping.shippingmethod",
                    ),
                ),
                (
                    "terms_document",
                    models.ForeignKey(
                        help_text="Wersja regulaminu zaakceptowana przy składaniu zamówienia",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="consents.consentdocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Zalogowany klient; pusty przy zamówieniu gościa",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zamówienie",
                "verbose_name_plural": "Zamówienia",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("sku", models.CharField(max_length=64)),
                (
                    "is_made_to_order",
                    models.BooleanField(
                        help_text="Czy wyrób powstaje dopiero po złożeniu zamówienia (ADR 0024)"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        help_text="Liczba sztuk pozycji, najwyżej 5",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit_price",
                    common.money.fields.MoneyAmountField(
                        help_text="Cena brutto jednego egzemplarza z chwili złożenia zamówienia",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Stawka podatku jako ułamek; pusta wyłącznie przy zwolnieniu",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("is_vat_exempt", models.BooleanField(default=False)),
                ("vat_exemption_basis", models.CharField(blank=True, max_length=200)),
                ("engraving_text", models.CharField(blank=True, max_length=50)),
                (
                    "engraving_price",
                    common.money.fields.MoneyAmountField(
                        default=0,
                        help_text="Cena grawerunku jednego egzemplarza z chwili złożenia",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="Rozmiar pierwszego egzemplarza, skopiowany z wariantu",
                        max_length=2,
                    ),
                ),
                (
                    "second_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                            ("16", "16"),
                            ("17", "17"),
                            ("18", "18"),
                            ("19", "19"),
                            ("20", "20"),
                            ("21", "21"),
                            ("22", "22"),
                            ("23", "23"),
                            ("24", "24"),
                            ("25", "25"),
                            ("26", "26"),
                        ],
                        help_text="Rozmiar drugiego egzemplarza pary (ADR 0024)",
                        max_length=2,
                    ),
                ),
                ("second_engraving_text", models.CharField(blank=True, max_length=50)),
                (
                    "discount_amount",
                    common.money.fields.MoneyAmountField(
                        default=0,
                        help_text="Rabat naliczony na tę pozycję; wypełni go bilet promocji",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        help_text="Kupiony wariant — do odnalezienia karty produktu, nie do wyceny",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pozycja zamówienia",
                "verbose_name_plural": "Pozycje zamówienia",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                django.db.models.functions.text.Lower("email"),
                name="order_email_lower_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="orders_orde_status_25e057_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("shipping_cost__gte", 0)),
                name="order_shipping_cost_is_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_amount__gte", 0), ("coupon_amount__gte", 0)
                ),
                name="order_reductions_are_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="order_item_quantity_is_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unit_price__gte", 0),
                    ("engraving_price__gte", 0),
                    ("discount_amount__gte", 0),
                ),
                name="order_item_amounts_are_not_negative",
            ),
        ),
    ]
