# Generated by Django 6.0.8 on 2026-09-24 02:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_orderitem_order_order_email_lower_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_requested",
            field=models.BooleanField(
                default=False,
                help_text="Klient poprosił o fakturę imienną — wystawiana na odbiorcę i adres z zamówienia (ADR 0026)",
            ),
        ),
        migrations.CreateModel(
            name="DocumentCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("confirmation", "Potwierdzenie zamówienia"),
                            ("invoice", "Faktura"),
                            ("correction", "Korekta"),
                        ],
                        max_length=16,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Licznik dokumentów",
                "verbose_name_plural": "Liczniki dokumentów",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "year"),
                        name="document_counter_kind_year_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("confirmation", "Potwierdzenie zamówienia"),
                            ("invoice", "Faktura"),
                            ("correction", "Korekta"),
                        ],
                        help_text="Rodzaj dokumentu; korekta przychodzi ze zwrotami",
                        max_length=16,
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Numer ciągły w obrębie rodzaju i roku"
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Rok numeracji — ten sam, co rok wystawienia"
                    ),
                ),
                ("issued_on", models.DateField(help_text="Data wystawienia dokumentu")),
                (
                    "object_key",
                    models.CharField(
                        help_text="Klucz PDF w buckecie `documents`, bez hosta i bucketa",
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Zamówienie, do którego wystawiono dokument",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument sprzedaży",
                "verbose_name_plural": "Dokumenty sprzedaży",
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "year", "number"),
                        name="sales_document_number_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "correction"), _negated=True),
                        fields=("order", "kind"),
                        name="sales_document_once_per_order",
                    ),
                ],
            },
        ),
    ]
