# Generated by Django 6.0.8 on 2026-09-24 03:38

import common.money.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_sales_document"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                help_text="Promocja aktywowana kodem wpisanym w koszyku",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="promotions.promotion",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_amount",
            field=common.money.fields.MoneyAmountField(
                default=0,
                help_text="Suma rabatów z promocji na pozycjach, przed podatkiem (ADR 0023)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="discount_amount",
            field=common.money.fields.MoneyAmountField(
                default=0,
                help_text="Rabat promocji naliczony na towar tej pozycji, przed podatkiem",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
