# Generated by Django 6.0.8 on 2026-09-24 18:45

import common.money.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_cart_promotion"),
        ("promotions", "0002_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                help_text="Kupon wpisany w koszyku — zapłata za towar po promocjach",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="promotions.coupon",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="coupon_amount",
            field=common.money.fields.MoneyAmountField(
                default=0,
                help_text="Kwota towaru pokryta kuponem, po promocjach (ADR 0011)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
