# Generated by Django 6.0.8 on 2026-09-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_cart_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="exchange_rate_on",
            field=models.DateField(
                blank=True,
                help_text="Dzień notowania kursu; pusty przy sprzedaży w złotych (ADR 0019)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="exchange_rate_source",
            field=models.CharField(
                blank=True,
                help_text="Źródło kursu (np. nbp); puste przy sprzedaży w złotych",
                max_length=64,
            ),
        ),
    ]
