# Generated by Django 6.0.8 on 2026-09-25 14:27

from django.db import migrations, models
from django.db.models import F


def backfill_delivered_at(apps, schema_editor) -> None:
    """Zamówienia dostarczone przed #193 nie mają daty doręczenia.

    `updated_at` to najlepsze dostępne przybliżenie: po `delivered` jedyną
    zmianą jest przejście w `returned`, więc przy statusie `delivered`
    ostatni zapis to zwykle właśnie doręczenie. `returned` zostaje puste —
    tam `updated_at` to chwila zwrotu, nie doręczenia.
    """
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(status="delivered", delivered_at__isnull=True).update(
        delivered_at=F("updated_at")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_order_exchange_rate_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Chwila przejścia w `delivered` — od niej biegną terminy zwrotu (`CONTEXT.md`, ReturnReason). Ustawiana raz, nigdy nadpisywana.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_delivered_at, migrations.RunPython.noop),
    ]
