# Generated by Django 6.0.8 on 2026-09-25 17:41

import common.money.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_order_delivered_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("withdrawal", "Odstąpienie od umowy"),
                            ("complaint", "Reklamacja"),
                            ("goodwill", "Zwrot dobrowolny"),
                        ],
                        help_text="Podstawa zwrotu — obowiązkowa",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Zgłoszone"),
                            ("resolved", "Rozpatrzone"),
                        ],
                        default="submitted",
                        max_length=16,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zgłoszenie zwrotu",
                "verbose_name_plural": "Zgłoszenia zwrotu",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ReturnRequestItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "claim_request",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("refund", "Zwrot pieniędzy"),
                            ("repair", "Naprawa"),
                            ("replacement", "Wymiana"),
                        ],
                        help_text="Żądanie reklamacyjne; puste przy innej podstawie",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje na rozpatrzenie"),
                            ("to_agree", "Do uzgodnienia"),
                            ("accepted", "Uwzględniona"),
                            ("rejected", "Odrzucona"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "restocked",
                    models.BooleanField(
                        default=False,
                        help_text="Towar wrócił na stan ruchem magazynowym `return`",
                    ),
                ),
                (
                    "decision_note",
                    models.TextField(
                        blank=True,
                        help_text="Uzasadnienie decyzji — obowiązkowe przy odrzuceniu",
                    ),
                ),
                (
                    "agreed_resolution",
                    models.CharField(
                        blank=True,
                        help_text="Uzgodniona forma, np. odkup po cenie złomu (pozycja do uzgodnienia)",
                        max_length=200,
                    ),
                ),
                (
                    "agreed_amount",
                    common.money.fields.MoneyAmountField(
                        blank=True,
                        help_text="Uzgodniona kwota w groszach, w walucie zamówienia",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.returnrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pozycja zgłoszenia zwrotu",
                "verbose_name_plural": "Pozycje zgłoszenia zwrotu",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="returnrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason", ""), _negated=True),
                name="return_request_reason_is_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="returnrequestitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="return_item_quantity_is_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="returnrequestitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("agreed_amount__isnull", True),
                    ("agreed_amount__gte", 0),
                    _connector="OR",
                ),
                name="return_item_agreed_amount_is_not_negative",
            ),
        ),
    ]
