# Generated by Django 6.0.8 on 2026-09-25 18:16

import common.money.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_return_request"),
        ("promotions", "0003_alter_promotion_requires_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="compensation_amount",
            field=common.money.fields.MoneyAmountField(
                blank=True,
                editable=False,
                help_text="Zwracana kwota w groszach; pusta, dopóki nie rozliczono",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="coupon",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                help_text="Kupon wydany z kuponowej części zwrotu",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="return_request",
                to="promotions.coupon",
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="refund_amount",
            field=common.money.fields.MoneyAmountField(
                default=0, editable=False, help_text="Pieniężna część zwrotu w groszach"
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="refund_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Identyfikator zwrotu u operatora",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("none", "Bez zwrotu pieniędzy"),
                    ("pending", "Zlecony u operatora"),
                    ("refunded", "Zwrócony"),
                    ("manual", "Do zwrotu ręcznego"),
                    ("manual_done", "Zwrócony przelewem"),
                ],
                default="none",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="settled_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="return_request",
            field=models.OneToOneField(
                blank=True,
                help_text="Rozliczony zwrot, który koryguje ten dokument (tylko korekta)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction",
                to="orders.returnrequest",
            ),
        ),
    ]
