# Generated by Django 6.0.8 on 2026-09-26 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_return_settlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequestitem",
            name="exchange_order",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                help_text="Zamówienie 0 zł wymiany na ten sam wariant (#198)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="return_exchange_item",
                to="orders.order",
            ),
        ),
    ]
