# Generated by Django 6.0.8 on 2026-10-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_returnrequestitem_exchange_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='reminded_at',
            field=models.DateTimeField(blank=True, help_text='Moment wysłania przypomnienia o koszyku (`CONTEXT.md`, CartReminder). Zmiana zawartości koszyka je zeruje — dopiero wtedy wolno wysłać kolejne.', null=True),
        ),
    ]
